version: "3.8"

services:
  php:
    build:
      context: ./php
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ../:/app:cached
      - ./php/zzz-php-config.ini:/usr/local/etc/php/conf.d/zzz-php-config.ini